<?php
/* company-billing-profiles-section.php

    Abstracted 2020-02-13 JM from company.php.
    
    Writes the billingProfiles section of the top-level company page directly to stdout. 
    
    This file can be included, using GET method, to write content inline when the page is first created, 
    or it can be called as AJAX to get an update for the section and then use jQuery replaceWith to put it in position.
    If it is called as AJAX, then INPUT $_REQUEST['companyId'] should be set; otherwise $company should already be defined.  
    
    The AJAX approach will typically be called from within the content generated by this file.
    
    EXAMPLES:
    include "company-billing-profiles-section.php"; // $company should already be defined
    
    $.ajax({
      url: "company-billing-profiles-section.php",
      data: {companyId: $companyId},
      success: function(data) {
          $('#billing-profiles-section').replaceWith(data);
      },
      dataType: 'text'
    });
*/

require_once './inc/config.php';
require_once './inc/access.php';

function writeBillingProfileTableStart() {
    echo '<table border="0">' . "\n";
        echo '<thead>' . "\n";
            echo '<tr>' . "\n";
                echo '<th>Name</th>' . "\n"; // a person's name, not name of billing profile
                echo '<th>Location</th>' . "\n";
                echo '<th>Other</th>' . "\n";
                echo '<th>&nbsp;</th>' . "\n";
            echo '</tr>' . "\n";
        echo '</thead>' . "\n";
        echo '<tbody>' . "\n";
}

function writeBillingProfileTableEnd() {
        echo '</tbody>' . "\n";
    echo '</table>' . "\n";
}
?>

<style>
 /* George: fancybox to small! So we changed frame size! */
.fancybox-wrap .fancybox-desktop .fancybox-type-iframe .fancybox-opened{
width:1100px!important;
margin-left:-120px!important;
}

.fancybox-skin{
    width:1090px!important;
    padding:0px!important;
    margin-left:-120px!important;
}
.fancybox-outer{
    width:1090px!important;
}
.fancybox-inner{
    width:1090px!important;
}
</style>

<?php
function writeOneBillingProfileRow($bp, $bgcolor) {
    $billingProfile = $bp['billingProfile'];
    $cpid = $billingProfile->getCompanyPersonId();
    echo '<tr ' . $bgcolor  . '>' . "\n";
        // "Name": person associated with the billingProfile (person who should be billed)
        // Blank if no such.
        echo '<td>';
        if (intval($cpid)){
            $cp = new CompanyPerson($cpid);
            $p = $cp->getPerson();
            echo $p->getFormattedName(1);
        }
        echo '</td>' . "\n";
        
        // "Location" (if one associated with the billing profile)
        echo '<td>';
        echo $bp['loc'];
        echo '</td>' . "\n";
    
        // "Other": nested table with various info about the billing profile
        echo '<td>'."\n";        
            echo '<table border="0" cellpadding="0" cellspacing="0" style="font-size:80%">'."\n";
                echo '<tr>';
                    echo '<td>Multiplier</td>';
                    echo '<td>' . $billingProfile->getMultiplier() . '</td>';
                echo '</tr>'."\n";
                echo '<tr>';
                    echo '<td>Dispatch</td>';
                    echo '<td>' . $billingProfile->getDispatch() . '</td>';
                echo '</tr>'."\n";
                echo '<tr>';
                    echo '<td>Grace Period</td>';
                    echo '<td>' . $billingProfile->getGracePeriod() . '</td>';
                echo '</tr>'."\n";
        
                echo '<tr>';
                    echo '<td>Terms</td>';
                    echo '<td>';
                    
                    $terms = getTerms();
                    foreach ($terms as $term) { 
                        if (intval($billingProfile->getTermsId()) == intval($term['termsId'])){
                            echo $term['termName'];
                        }
                    }							
                    echo '</td>';
                echo '</tr>'."\n";
        
                echo '<tr>';
                    echo '<td>Language</td>';
                    echo '<td>';                    
                        $files = getContractLanguageFiles();
                        foreach ($files as $file) {
                            if ($billingProfile->getContractLanguageId() == $file['contractLanguageId']){
                                echo $file['fileName'];
                            }
                        }
                    echo '</td>';
                echo '</tr>'."\n";
            echo '</table>'."\n";
        echo '</td>' . "\n";
        
        // Link to edit the billingProfile on this row in a fancybox.
        echo '<td valign="middle">';
            if ($billingProfile->getActive()) {
                if ($bp['isPrimary']) {
                    echo '<b>PRIMARY</b>&nbsp;<button class="removeprimary" ' . 
                         'data-companyid="' .intval($billingProfile->getCompanyId()) . '" id="removePrimary' .intval($billingProfile->getCompanyId()) . '" >Undo</button><br />';
                } else {
                    echo '<button class="addprimary" ' . 
                         'data-billingprofileid="' . intval($billingProfile->getBillingProfileId()) . '" ' .
                         'data-companyid="' .intval($billingProfile->getCompanyId()) . '" id="makePrimary' .intval($billingProfile->getBillingProfileId()) . '">Make primary</button><br />';
                }
                echo '<button class="deactivate" ' . 
                         'data-billingprofileid="' . intval($billingProfile->getBillingProfileId()) . '" id="deactivateBillingProfile' . intval($billingProfile->getBillingProfileId()) . '">Deactivate</button><br />';
            } else {
                echo '<button class="activate" ' . 
                         'data-billingprofileid="' . intval($billingProfile->getBillingProfileId()) . '" id="activateBillingProfile' . intval($billingProfile->getBillingProfileId()) . '">Activate</button><br />';
            }
            echo '<a data-fancybox-type="iframe" id="iframeEditBillingProfile' . intval($billingProfile->getBillingProfileId()) . '" class="fancyboxIframe fancybox" href="/fb/editbillingprofile.php?billingProfileId=' . intval($billingProfile->getBillingProfileId()) . '"><button>Edit</button></a>';
        echo '</td>' . "\n";
    echo '</tr>' . "\n";
} // END function writeOneBillingProfileRow

function writeButtonHandlers($companyId) {
?>
<script>
    function reloadBillingProfiles() {
        $.ajax({
          url: "/company-billing-profiles-section.php",
          data: {companyId: <?php echo $companyId; ?>},
          success: function(data) {
              $('#billing-profiles-section').replaceWith(data);
          },
          dataType: 'text'
        });
    }
    
    function doAction(action, billingProfileId, companyId) {
        let data = {
            act: action
        }
        if (billingProfileId) {
            data.billingProfileId = billingProfileId; 
        }
        if (companyId) {
            data.companyId = companyId; 
        }
        $.ajax({
            url: "/ajax/billingprofileaction.php",
            data: data,
            success: function(data, textStatus, jqXHR) {
                if (data['status']) {
                    if (data['status'] == 'success') {
                        reloadBillingProfiles();
                    } else {
                        alert('error from ajax/billingprofileaction.php, action=' + action+ ': ' + data['error']);
                    }
                } else {
                    alert('error no status from ajax/billingprofileaction.php, action=' + action+ '');
                }
            },
            error: function(jqXHR, textStatus, errorThrown) {
                alert('error in AJAX protocol or in called function ajax/billingprofileaction.php, action=' + action+ ', see server log');
            }
        });
    } // END function doAction
    
    // Remove any prior handlers generated from this set.
    $(document).off('.billing-profile-handler');
    
    $(document).on('click.billing-profile-handler', '#billing-profiles-section button.removeprimary', function() {
        let $this = $(this);
        doAction('removePrimary', null, $this.data('companyid'));
    });
    $(document).on('click.billing-profile-handler', '#billing-profiles-section button.addprimary', function() {
        let $this = $(this);
        doAction('addPrimary', $this.data('billingprofileid'), $this.data('companyid'));
    });
    $(document).on('click.billing-profile-handler', '#billing-profiles-section button.activate', function() {
        let $this = $(this);
        doAction('activate', $this.data('billingprofileid'), null);
    });
    $(document).on('click.billing-profile-handler', '#billing-profiles-section button.deactivate', function() {
        let $this = $(this);
        doAction('deactivate', $this.data('billingprofileid'), null);
    });
</script>
<?php
} // END function writeButtonHandlers

if (isset($company)) {
    // We're good
} else if (array_key_exists('companyId', $_REQUEST)) {
    $company = new Company($_REQUEST['companyId']);
}


if (isset($company) && intval($company->getCompanyId())) {
    echo '<div id="billing-profiles-section" class="full-box clearfix">' . "\n";
        writeButtonHandlers($company->getCompanyId());
        $bps = $company->getBillingProfiles();
        
        // We always show this section, even if it is empty.
        echo '<h2 class="heading">Active billing Profile Templates</h2>' . "\n";
        // link to addbilling profile.php in a fancybox
        echo '<a data-fancybox-type="iframe" id="iframeLinkAddBillingProfile" class="button add show_hide fancyboxIframe fancybox" ' . 
             'href="/fb/addbillingprofile.php?companyId=' . $company->getCompanyId() . '">Add</a>' . "\n";

        // Are there any active templates?        
        $hasActive = false;
        foreach ($bps as $bp) {
            if ($bp['billingProfile']->getActive()) {
                $hasActive = true;
                break;
            }
        }
        if ($hasActive) {             
            writeBillingProfileTableStart();
            
            $bgcolor  = ' bgcolor="#eeeeee" ';
            foreach ($bps as $bp) {
                if ($bp['isPrimary']) {
                    writeOneBillingProfileRow($bp, $bgcolor);
                    $bgcolor  = '';
                }
            }
            
            foreach ($bps as $bp) {
                if ($bp['billingProfile']->getActive() && !$bp['isPrimary']) {
                    writeOneBillingProfileRow($bp, $bgcolor);
                    if ($bgcolor) {
                        $bgcolor  = '';
                    } else {
                        $bgcolor = ' bgcolor="#eeeeee" ';
                    }
                }
            }
            writeBillingProfileTableEnd();
        } else {
            echo "<center>There are no active billing profiles for this client.</center>\n"; 
        }
        
        // Are there any inactive templates?        
        $hasInactive = false;
        foreach ($bps as $bp) {
            if ($bp['billingProfile']->getActive() == 0) {
                $hasInactive = true;
                break;
            }
        }
        
        if ($hasInactive) {
            echo '<hr color="gray">';
            echo '<h2 class="heading">Inactive billing Profile Templates</h2>' . "\n";
            writeBillingProfileTableStart();
            
            $bgcolor  = ' bgcolor="#eeeeee" ';
            foreach ($bps as $bp) {
                if ($bp['billingProfile']->getActive()==0) {
                    writeOneBillingProfileRow($bp, $bgcolor);
                    if ($bgcolor) {
                        $bgcolor  = '';
                    } else {
                        $bgcolor = ' bgcolor="#eeeeee" ';
                    }
                }
            }
            writeBillingProfileTableEnd();
        }
    echo '</div>' . "\n";
} else {
    echo '<div>company-billing-profiles-section.php cannot identify company.</div>'; 
}
?>

<script type="text/javascript">
    $(document).ready(function() {
        $('a.fancybox').fancybox({
            'type': 'iframe'
        });
    });
</script>
